__title__ = 'ambassadress'
__description__ = 'Client for RedSMS GET API.'
__url__ = 'https://github.com/Hack-The-Travel/ambassadress'
__version__ = '0.0.1'
__author__ = 'Sergey Popinevskiy'
__author_email__ = 'sergey.popinevskiy@gmail.com'
__license__ = ''
